//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mom
    {
        public int MomID { get; set; }
        public string ProjectInfo { get; set; }
        public string TimeStamp { get; set; }
        public string MomContent { get; set; }
        public string MomFile { get; set; }
    }
}
