//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_projectdetails
    {
        public int ProjectID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> DomainTeam { get; set; }
        public Nullable<int> DomainLead { get; set; }
        public Nullable<int> TechLead { get; set; }
        public Nullable<int> QCLead { get; set; }
        public string DomainResource { get; set; }
        public string TechResource { get; set; }
        public string Modules { get; set; }
        public string EstimatedCost { get; set; }
        public string ProjectLogo { get; set; }
        public string ProjectDetails { get; set; }
        public string StartDate { get; set; }
        public string Duration { get; set; }
        public Nullable<int> TechTeam { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ProjectType { get; set; }
        public string ClientName { get; set; }
        public string TotalCost { get; set; }
        public string CurrencyType { get; set; }
    }
}
