//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_module
    {
        public int ModuleID { get; set; }
        public string ModuleTitle { get; set; }
        public string ModuleWeight { get; set; }
        public string PercentComplete { get; set; }
        public string ModuleTeamInfo { get; set; }
        public Nullable<int> ProjectInfo { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ModuleDescription { get; set; }
        public string ModuleFiles { get; set; }
    }
}
