//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjectEstimate
    {
        public int ProjectID { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> TechDuration { get; set; }
        public Nullable<int> AnalystDuration { get; set; }
        public string TechResource { get; set; }
        public string AnalystResource { get; set; }
        public string DeveloperDuration { get; set; }
        public string BADuration { get; set; }
        public string QCDuration { get; set; }
        public string LeadDuration { get; set; }
        public string DomainDuration { get; set; }
        public string ModuleCost { get; set; }
    }
}
